default_language_version:
  python: python3.11
repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "0.6.2"

    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [ -C ]
